name: CI/CD Workflow
on:
  push:
    branches:
      - '*'
    # Trigger build and test on pull request to main
    # This event will trigger the jobs on any pull request, not just those on the main branch
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Build app
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Trigger deploy on push to main branch
    # if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    - name: Deploy app
      run: |
        doctl auth init -t ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
        doctl compute scp --recursive ./build root@68.183.111.11:/var/www/badging.chaoss.io
